spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      reader:
        sql:
          name: pagingReader
          query: "select * from cars"
          selectClause: "select *"
          fromClause: "from cars"
          whereClause: "where 1 = 1"
          sortKey: "car_id"
          order: ASCENDING
          pageSize: 100
          fetchSize: 100
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mytmpdb;INIT=RUNSCRIPT FROM 'classpath:init.sql'
    username: sa
    password: ""
  mysql-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/tmpdb_spark
    username: tmpdb_spark_user
    password: tmpdb_spark_user
  h2:
    console:
      enabled: true
      path: /h2-console
